### ISSUE TITLE
Some Improvements

### ISSUE THREAD

**Issue by D3SOX** [MAPReiff/ShadowRePlay-Linux#4]
Hi,

thanks for making the script. I have some improvements for it.

- Make the variables accessible as parameters
- Support for multi-monitors
- Dependency checking
- Use XDG Videos directory
- Notification on save

I forked the project and made some commits to it. (See <https://github.com/D3S0X/Shadowplay-Linux>).
Maybe you want to implement something of it in your version too

**Comment by terencode** [comment]
It would also be nice to make the shortcut only working when inside a program, maybe  with a LD_PRELOAD thingy like gamemode and mangohud do with `gamemoderun` and `mangohud`.
This could then maybe not require the daemon to always be running.

**Comment by D3SOX** [comment]
I don't know why you don't respond to issues and comments on the AUR (I left you one at https://aur.archlinux.org/packages/shadowreplay-git/)
Also this project seems to be unmaintained. I'm closing this now. Feel free to re-open.
If anyone is searching for an alternative I recommend https://github.com/matanui159/ReplaySorcery
