### ISSUE TITLE
Shadowplay trademark

### ISSUE THREAD

**Issue by C0rn3j** [MAPReiff/ShadowRePlay-Linux#9]
Nvidia has the term Shadowplay trademarked, as per their own website - https://www.nvidia.com/en-us/about-nvidia/legal-info/

Wouldn't it be a better idea to name the project something else that doesn't clash against Nvidia's notice `NVIDIA's trademarks may be used publicly with permission only from NVIDIA`?

One idea would be Shadowreplay.

Calling the features shadowplay-like, similar to how [gpu-screen-recorder](https://github.com/DEC05EBA/gpu-screen-recorder) does might be an idea.

_Obvious disclaimer - not a lawyer._

**Comment by MAPReiff** [comment]
Thanks for the input, took your suggestion of ShadowRePlay. https://github.com/MAPReiff/ShadowRePlay-Linux/commit/37213c23fe8d32e234f9cfd17ae05a3959ff889f
